version: "3.3"

services:
  otc-web:
    container_name: otc-web
    build:
      context: .
    command: >
       sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:.
    ports:
      - "8000:8000"  
    env_file:
      - ./otcexchange/.env
    networks:
      - kawdoon

  crypto-db:
    image: postgres:14-alpine
    user: postgres
    environment:
      - POSTGRES_DB=otcexchange
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypass
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - kawdoon    