# Generated by Django 4.2.13 on 2024-06-02 10:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('balance_chart', models.JSONField(blank=True, null=True)),
                ('send_with_sms', models.BooleanField(default=True)),
                ('send_with_email', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/avatars')),
                ('approve_rules', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('otp_enabled', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_base32', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_auth_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_blocked', models.BooleanField(blank=True, default=False, null=True)),
                ('change_password_time', models.DateTimeField(blank=True, null=True)),
                ('user_main_info_check_status', models.CharField(blank=True, choices=[('inprogress', 'in progress'), ('matched', 'matched'), ('failed', 'failed')], default='inprogress', max_length=12, null=True)),
                ('user_main_info_check_status_msg', models.TextField(blank=True, null=True)),
                ('user_card_info_check_status', models.CharField(blank=True, choices=[('inprogress', 'in progress'), ('matched', 'matched'), ('failed', 'failed')], default='inprogress', max_length=20, null=True)),
                ('user_card_info_check_status_msg', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DefaultLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('level', models.IntegerField(choices=[(1, 'LEVEL 1'), (2, 'LEVEL 2'), (3, 'LEVEL 3'), (4, 'LEVEL 4'), (5, 'LEVEL 5'), (6, 'LEVEL 6'), (7, 'LEVEL 7')], default=1, unique=True)),
                ('convert', models.BigIntegerField(default=0)),
                ('deposit_irr', models.BigIntegerField(default=0)),
                ('deposit_crypto', models.BigIntegerField(default=0)),
                ('withdraw_irr', models.BigIntegerField(default=0)),
                ('withdraw_crypto', models.BigIntegerField(default=0)),
                ('buy', models.BigIntegerField(default=0)),
                ('sell', models.BigIntegerField(default=0)),
                ('turnover', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAuthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('kyc_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('kyc_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('nation_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='auth/card_image')),
                ('backside_card_image', models.ImageField(blank=True, null=True, upload_to='auth/backside_card_image')),
                ('verification_video', models.FileField(blank=True, null=True, upload_to='auth/verification_video')),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='female', max_length=6)),
                ('job', models.CharField(blank=True, default='Trader', max_length=100, null=True)),
                ('approximate_monthly_deposit', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('level', models.IntegerField(choices=[(1, 'LEVEL 1'), (2, 'LEVEL 2'), (3, 'LEVEL 3'), (4, 'LEVEL 4'), (5, 'LEVEL 5'), (6, 'LEVEL 6'), (7, 'LEVEL 7')], default=1)),
                ('convert', models.BigIntegerField(default=0)),
                ('deposit_irr', models.BigIntegerField(default=0)),
                ('deposit_crypto', models.BigIntegerField(default=0)),
                ('withdraw_irr', models.BigIntegerField(default=0)),
                ('withdraw_crypto', models.BigIntegerField(default=0)),
                ('buy', models.BigIntegerField(default=0)),
                ('sell', models.BigIntegerField(default=0)),
                ('turnover', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserBankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('account_card_number', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('iban', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KYCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nation_code_result', models.BooleanField(blank=True, default=False)),
                ('birth_date_result', models.BooleanField(blank=True, default=False)),
                ('account_card_number_result', models.BooleanField(blank=True, default=False)),
                ('card_image_result', models.BooleanField(blank=True, default=False)),
                ('backside_card_image_result', models.BooleanField(blank=True, default=False)),
                ('verification_video_result', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='auth_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userauthinfo'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userlevel'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
